# Generated by Django 5.1.6 on 2025-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Jain (Deemed-to-be University)', max_length=200),
        ),
    ]
