# Generated by Django 5.1.6 on 2025-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='interests',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='superpower',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
