# Generated by Django 5.1.6 on 2025-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_registration_interests_registration_superpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='interests',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='superpower',
            field=models.CharField(max_length=500000),
        ),
    ]
