# Generated by Django 5.1.6 on 2025-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_registration_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Registration Settings',
            },
        ),
    ]
