# Generated by Django 5.1.6 on 2025-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_registrationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='about_yourself',
        ),
        migrations.AlterField(
            model_name='registration',
            name='domains',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=100000),
        ),
    ]
