# Generated by Django 5.1.6 on 2025-03-01 12:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_challengeparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
