# Generated by Django 5.1.6 on 2025-03-01 13:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_challenge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='requirements',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='technology_stack',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Technology Stack'),
        ),
    ]
