# Generated by Django 5.1.6 on 2025-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_challenge_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipation',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
