# Generated by Django 5.1.6 on 2025-03-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_userprofile_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together=set(),
        ),
    ]
