# Generated by Django 5.1.6 on 2025-03-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_challengeparticipation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('tel', 'Phone'), ('team', 'Team Name')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='myapp.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
